// comenzi
#define LOGIN '0'
#define LOGOUT '#'
#define REGISTER '1'
#define EXIT '2'
#define VALIDATE_USERNAME '3'
#define ADD_SONG '4'
#define DISPLAY_NORMAL '5'
#define DISPLAY_GENRES '6'
#define VOTE_SONG '7'
#define ADD_COMMENT '8'
#define DENY_VOTE '9'
#define DELETE_SONG '-'